apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-todo
  template:
    metadata:
      labels:
        app: react-todo
    spec:
      containers:
      - name: react-todo
        image: todo-react:1.0   # Use your Docker image
        imagePullPolicy: Never        # Important for local images
        ports:
        - containerPort: 80